### ISSUE TITLE
<documentation> Provide List of all options.

### ISSUE THREAD

**Issue by xaxa-0x3F** [CTK-WARRIOR/ctk-anime-scraper#5]
Hello, can someone please provide me a list of all options.

**Comment by PaimonWheeWhee** [comment]
All options of what

**Comment by PaimonWheeWhee** [comment]
If you mean a list of all the functions [here you go](https://github.com/CTK-WARRIOR/ctk-anime-scraper/tree/main/src/Functions)

**Comment by CTK-WARRIOR** [comment]
Sorry, documentation is not out yet as we are working on new version of the package but you can see all the function name on this file: https://github.com/CTK-WARRIOR/ctk-anime-scraper/blob/main/src/index.js

**Comment by geetesh07** [comment]
Um can anyone give a quick tutorial on how it is done? Would mean a lot!
